### ISSUE TITLE
Is this pkg really work?

### ISSUE THREAD

**Issue by shenyp09** [go-hep/rootio#3]
package main

import (
    "fmt"

```
"github.com/go-hep/rootio"
```

)

func main() {
    f, _ := rootio.Open("data150.root")
    defer f.Close()
    obj, _ := f.Get("tree")
    tree := obj.(*rootio.Tree)
    fmt.Printf("entries= %v\n", tree.Entries())
}

panic: runtime error: invalid memory address or nil pointer dereference
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xf0 pc=0x3baec]

goroutine 1 [running]:
runtime.panic(0xc7880, 0x1e1899)
    /Users/Fermi/dev/src/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/go-hep/rootio.(_File).Close(0x0, 0xc, 0x0)
    /Users/Fermi/Documents/Go/src/github.com/go-hep/rootio/file.go:290 +0x2c
runtime.panic(0xc7880, 0x1e1899)
    /Users/Fermi/dev/src/go/src/pkg/runtime/panic.c:248 +0x106
github.com/go-hep/rootio.(_File).Get(0x0, 0xe58a0, 0x4, 0x24ee80, 0x210288370, ...)
    /Users/Fermi/Documents/Go/src/github.com/go-hep/rootio/file.go:349 +0x6a
main.main()
    /Users/Fermi/Documents/Go/src/examples/main.go:12 +0x7b

This must be the simplest code, I think. But it still cannot work. May you give an example about how to work with this package?

**Comment by sbinet** [comment]
development will resume. soon. (closing for now)
